#define mid_repeat_list                 1
#define mid_repeat_track                2
#define mid_shuffle                     3
#define mid_autoswitching               4
#define mid_settings                    5
#define midc_title                      6
#define midc_album                      7
#define midc_artist                     8
#define midc_oartist                    9
#define midc_composer                   10
#define midc_lyricist                   11
#define midc_band                       12
#define midc_copyright                  13
#define midc_publisher                  14
#define midc_encodedby                  15
#define midc_genre                      16
#define midc_year                       17
#define midc_url                        18
#define midc_ourl                       19
#define midc_filepath                   20
#define midc_filename                   21
#define midc_bpm                        22
#define midc_track                      23
#define midc_index                      24
#define mid_title                       25
#define mid_sort_filename               26
#define mid_unsort                      27
#define mid_addfiles                    28
#define mid_add_dir                     29
#define mid_add_mlib                    30
#define mid_switch_sindex               31
#define menu_edittags                   32
#define mid_removesel                   33
#define mid_removeall                   34
#define mid_removeml                    35
#define mid_edittags                    36
#define mid_addtoplaylist               37
#define mid_loadpl                      38
#define mid_savepl                      39
#define mid_import                      40
#define mid_export                      41
#define menu_save                       42
#define menu_remove                     43
#define menu_options                    44
#define menu_sort                       45
#define mid_adddirs                     46
#define mid_tray                        47
#define mid_experimental                48
#define midc_font                       49
#define mid_preview						50
#define mid_preview_stop				51
#define mid_loadtracks                  52
#define mid_seldrive                    53